[project]
name = "rpg-characters"
description = "Stylized RPG character prompt generator for ComfyUI. Supports standard and Ollama-based prompts, works with SD, SDXL, Flux, and more."
version = "2.4.0"
license = {file = "LICENSE"}

[project.urls]
Repository = "https://github.com/lord-lethris/ComfyUI-RPG-Characters"
Documentation = "https://github.com/lord-lethris/ComfyUI-RPG-Characters/wiki"
"Bug Tracker" = "https://github.com/lord-lethris/ComfyUI-RPG-Characters/issues"

[tool.comfy]
PublisherId = "lord-lethris"
DisplayName = "ComfyUI-RPG-Characters"
Icon = "https://raw.githubusercontent.com/lord-lethris/ComfyUI-RPG-Characters/main/icon.png"
includes = []