CLASS_DATA = {
    "No Class": {"prompt": "is a neutral class", "negative_prompt": "is a class of Alchemist, is a class of Anti-Paladin, is a class of Assassin, is a class of Barbarian, is a class of Bard, is a class of Beastmaster, is a class of Butler, is a class of Cavalier, is a class of Cleric, is a class of Druid, is a class of Elementalist, is a class of Fighter, is a class of Illusionist, is a class of Illusionist, is a class of Mage, is a class of Monk, is a class of Necromancer, is a class of Paladin, is a class of professor, is a class of Ranger, is a class of Rogue, is a class of Samurai , is a class of Shadowdancer, is a class of Shaman, is a class of Sorcerer, is a class of Stalker, is a class of Swashbuckler, is a class of Thief-Acrobat, is a class of Witch, is a class of Wizard"},
    "Alchemist (a variant of the Wizard)": {"prompt": "is a class of Alchemist", "negative_prompt": ""},
    "Anti-Paladin (a villainous variant of the Paladin)": {"prompt": "is a class of Anti-Paladin", "negative_prompt": ""},
    "Assassin (a type of rogue with a focus on killing)": {"prompt": "is a class of Assassin", "negative_prompt": ""},
    "Barbarian (variant of the fighter)": {"prompt": "is a class of Barbarian", "negative_prompt": ""},
    "Bard": {"prompt": "is a class of Bard", "negative_prompt": ""},
    "Beastmaster": {"prompt": "is a class of Beastmaster", "negative_prompt": ""},
    "Butler": {"prompt": "is a class of Butler", "negative_prompt": ""},
    "Cavalier (a specialized fighter with a code of honor)": {"prompt": "is a class of Cavalier", "negative_prompt": ""},
    "Cleric": {"prompt": "is a class of Cleric", "negative_prompt": ""},
    "Druid": {"prompt": "is a class of Druid", "negative_prompt": ""},
    "Elementalist (subclass of Mage)": {"prompt": "is a class of Elementalist", "negative_prompt": ""},
    "Fighter": {"prompt": "is a class of Fighter", "negative_prompt": ""},
    "Illusionist (specialist wizard)": {"prompt": "is a class of Illusionist", "negative_prompt": ""},
    "Mage": {"prompt": "is a class of Mage", "negative_prompt": ""},
    "Monk": {"prompt": "is a class of Monk", "negative_prompt": ""},
    "Necromancer (specialist mage)": {"prompt": "is a class of Necromancer", "negative_prompt": ""},
    "Paladin": {"prompt": "is a class of Paladin", "negative_prompt": ""},
    "Professor": {"prompt": "is a class of professor", "negative_prompt": ""},
    "Ranger": {"prompt": "is a class of Ranger", "negative_prompt": ""},
    "Rogue (Thief)": {"prompt": "is a class of Rogue", "negative_prompt": ""},
    "Samurai ": {"prompt": "is a class of Samurai ", "negative_prompt": ""},
    "Shadowdancer": {"prompt": "is a class of Shadowdancer", "negative_prompt": ""},
    "Shaman (a variant of the druid or cleric with a focus on spiritual and nature magic)": {"prompt": "is a class of Shaman", "negative_prompt": ""},
    "Sorcerer (specialist mage)": {"prompt": "is a class of Sorcerer", "negative_prompt": ""},
    "Stalker": {"prompt": "is a class of Stalker", "negative_prompt": ""},
    "Swashbuckler": {"prompt": "is a class of Swashbuckler", "negative_prompt": ""},
    "Thief-Acrobat (a variant of the rogue with enhanced acrobatic skills)": {"prompt": "is a class of Thief-Acrobat", "negative_prompt": ""},
    "Witch (subclass of Mage)": {"prompt": "is a class of Witch", "negative_prompt": ""},
    "Wizard": {"prompt": "is a class of Wizard", "negative_prompt": ""},
}