HAIR_STYLE_DATA = {
# =========================
# AD&D / Base Hair
# =========================
    "Bald": {"prompt": "with a bald head", "negative_prompt": "hair on head"},
    "Afro": {"prompt": "with {short|medium|large} Afro hair, {rounded|full and natural|softly textured}", "negative_prompt": ""},
    "Beehive haircut": {"prompt": "with Beehive haircut", "negative_prompt": ""},
    "Bleached spikes": {"prompt": "with Bleached spikes", "negative_prompt": ""},
    "Blunt bob": {"prompt": "with Blunt bob", "negative_prompt": ""},
    "Bob": {"prompt": "with Bob haircut", "negative_prompt": ""},
    "Bowl cut": {"prompt": "with bowl cut hair", "negative_prompt": ""},
    "Box braids": {"prompt": "with Box braids", "negative_prompt": ""},
    "Bushy": {"prompt": "with {short|medium|long} bushy hair, {thick|voluminous|slightly unruly}", "negative_prompt": ""},
    "Buzz cut": {"prompt": "with Buzz cut", "negative_prompt": ""},
    "Chignon": {"prompt": "with Chignon", "negative_prompt": ""},
    "Cloudy": {"prompt": "with {soft|voluminous|billowing} cloudy hair, {wavy|curly|fluffy} texture", "negative_prompt": ""},
    "Cornrows Hair": {"prompt": "with Cornrows Hair", "negative_prompt": ""},
    "Crimped": {"prompt": "with Crimped hair", "negative_prompt": ""},
    "Curly bob": {"prompt": "with Curly bob", "negative_prompt": ""},
    "Curly Frizzy": {"prompt": "with {short|medium|long} curly frizzy hair, {voluminous|softly textured|wild and natural}", "negative_prompt": ""},
    "Double Bun": {"prompt": "with Double Bun", "negative_prompt": ""},
    "Dreadlocks": {"prompt": "with {short|medium|long} dreadlocks, {neatly maintained|thick and natural|slightly loose}", "negative_prompt": ""},
    "Fishtail braid": {"prompt": "with Fishtail braid", "negative_prompt": ""},
    "French twist": {"prompt": "with French twist", "negative_prompt": ""},
    "High Ponytail": {"prompt": "with High Ponytail", "negative_prompt": ""},
    "Long ponytail": {"prompt": "with {long|very long} ponytail, {high|mid-height|low} placement and {sleek|wavy|slightly tousled} hair", "negative_prompt": ""},
    "Long straight": {"prompt": "with {long|very long} straight hair, {sleek|flowing|slightly wind-swept}", "negative_prompt": ""},
    "Long with bangs": {"prompt": "with {long|very long} hair with {straight|soft|wispy} bangs, {sleek|flowing|slightly tousled}", "negative_prompt": ""},
    "Loose Curly Afro": {"prompt": "with Loose Curly Afro hair", "negative_prompt": ""},
    "Mohawk": {"prompt": "with Mohawk", "negative_prompt": ""},
    "Pixie cut": {"prompt": "with Pixie cut", "negative_prompt": ""},
    "Pompadour haircut": {"prompt": "with Pompadour haircut", "negative_prompt": ""},
    "Quiff haircut": {"prompt": "with Quiff haircut", "negative_prompt": ""},
    "Ringlets": {"prompt": "with Hair ringlets", "negative_prompt": ""},
    "Short": {"prompt": "with {short|very short} hair, {neatly trimmed|slightly tousled|textured}", "negative_prompt": ""},
    "Short curly": {"prompt": "with {short|very short} curly hair, {tight curls|soft curls|textured curls}", "negative_prompt": ""},
    "Short curly pixie cut": {"prompt": "with Short curly pixie cut", "negative_prompt": ""},
    "Shoulder length straight": {"prompt": "with shoulder-length straight hair, {sleek|flowing|slightly tousled}", "negative_prompt": ""},
    "Shoulder Length with Bangs": {"prompt": "with Shoulder Length Hair with Bangs", "negative_prompt": ""},
    "Side braid": {"prompt": "with Side braid", "negative_prompt": ""},
    "Side Part Comb-Over": {"prompt": "with Side Part Comb-Over Hairstyle With High Fade", "negative_prompt": ""},
    "Spiky hair": {"prompt": "with Spiky hair", "negative_prompt": ""},
    "Stacked Curls in Short Bob": {"prompt": "with Stacked Curls in Short Bob", "negative_prompt": ""},
    "Tomboy Cut": {"prompt": "with Tomboy Cut", "negative_prompt": ""},
    "Twin braids": {"prompt": "with Twin braids", "negative_prompt": ""},
    "Twintails": {"prompt": "with Twintails hair", "negative_prompt": ""},
    "Updo": {"prompt": "with Updo hair", "negative_prompt": ""},
    "Very long wave": {"prompt": "with {very long|extremely long} wavy hair, {flowing|voluminous|slightly wind-swept}", "negative_prompt": ""},
    "Wavy": {"prompt": "with {short|medium|long} wavy hair, {softly flowing|voluminous|slightly tousled}", "negative_prompt": ""},

# =========================
# Sci-Fi / Futuristic Hairstyles
# =========================

    "Asymmetrical Cut": {"prompt": "with Asymmetrical haircut, futuristic style", "negative_prompt": ""},
    "Undercut": {"prompt": "with Undercut hairstyle, cyberpunk style", "negative_prompt": ""},
    "Shaved Sides": {"prompt": "with Shaved Sides, futuristic cyberpunk haircut", "negative_prompt": ""},
    "Neon Streaks": {"prompt": "with hair featuring Neon Streaks, cyberpunk style", "negative_prompt": ""},
    "LED Hair": {"prompt": "with hair illuminated with subtle LED strands, cyberpunk aesthetic", "negative_prompt": ""},
    "Hawk Fade": {"prompt": "with Hawk Fade hairstyle, cyberpunk futuristic look", "negative_prompt": ""},
    "Synthetic Braids": {"prompt": "with Synthetic braids, futuristic cyberpunk style", "negative_prompt": ""},
    "Dreadhawk": {"prompt": "with Dreadhawk hairstyle, cyberpunk twist on Mohawk", "negative_prompt": ""},
    "Chrome Hair": {"prompt": "with Chrome-colored hair, metallic cyberpunk aesthetic", "negative_prompt": ""},
    "Iridescent Hair": {"prompt": "with Iridescent or Holographic hair, futuristic cyberpunk style", "negative_prompt": ""},
    "Tech Topknot": {"prompt": "with Tech Topknot, cyberpunk-inspired hairstyle", "negative_prompt": ""},
    "Shaved Pattern": {"prompt": "with Shaved Pattern designs on head, cyberpunk style", "negative_prompt": ""},
    "Spiked Mohawk": {"prompt": "with Spiked Mohawk, cyberpunk variant", "negative_prompt": ""},
    "Layered Neon Bob": {"prompt": "with Layered Bob haircut with Neon highlights, cyberpunk style", "negative_prompt": ""},
}