RACE_DATA = {
    "Human": {"prompt": "(Solo) 1Human", "negative_prompt": ""},
    "Elf": {"prompt": "(Solo) 1Elf", "negative_prompt": ""},
    "High Elf": {"prompt": "(Solo) 1High Elf", "negative_prompt": ""},
    "Wood Elf": {"prompt": "(Solo) 1Wood Elf", "negative_prompt": ""},
    "Dark Elf (Drow)": {"prompt": "(Solo) 1Dark Elf, Drow", "negative_prompt": ""},
    "Wild Elf (Grugach)": {"prompt": "(Solo) 1Wild Elf, Grugach", "negative_prompt": ""},
    "Aquatic Elf": {"prompt": "(Solo) 1Aquatic Elf", "negative_prompt": ""},
    "Half-Elf": {"prompt": "(Solo) 1Half-Elf, (Human:0.6) (Elf:0.4)", "negative_prompt": ""},
    "Dwarf": {"prompt": "(Solo) 1Dwarf", "negative_prompt": ""},
    "Hill Dwarf": {"prompt": "(Solo) 1Hill Dwarf", "negative_prompt": ""},
    "Mountain Dwarf": {"prompt": "(Solo) 1Mountain Dwarf", "negative_prompt": ""},
    "Duergar (Gray Dwarf)": {"prompt": "(Solo) 1Duergar, Gray Dwarf", "negative_prompt": "fangs, horns"},
    "Halfling": {"prompt": "(Solo) 1Halfling", "negative_prompt": ""},
    "Hairfoot Halfling": {"prompt": "(Solo) 1Hairfoot Halfling", "negative_prompt": ""},
    "Stout Halfling": {"prompt": "(Solo) 1Stout Halfling", "negative_prompt": ""},
    "Tallfellow Halfling": {"prompt": "(Solo) 1Tallfellow Halfling", "negative_prompt": ""},
    "Gnome": {"prompt": "(Solo) 1Gnome", "negative_prompt": ""},
    "Rock Gnome": {"prompt": "(Solo) 1Rock Gnome", "negative_prompt": ""},
    "Forest Gnome": {"prompt": "(Solo) 1Forest Gnome", "negative_prompt": ""},
    "Deep Gnome (Svirfneblin)": {"prompt": "(Solo) 1Svirfneblin, Deep Gnome, (grey complexation, weathered grey skin)", "negative_prompt": "hat"},
    "Orc": {"prompt": "(Solo) 1(Orc with tusks:1.5)", "negative_prompt": ""},
    "Half-Orc": {"prompt": "(Solo) 1Half-Orc, (Human:0.6) (Orc:0.4)", "negative_prompt": ""},
    "Aarakocra": {"prompt": "(Solo) 1Aarakocra", "negative_prompt": ""},
    "Tiefling": {"prompt": "(Solo) 1Tiefling, ({brick red|ruddy tan|human} Skin tone:1.3)", "negative_prompt": ""},
    "Aasimar": {"prompt": "(Solo) 1Aasimar, ({Pale|Pale Brown|dark brown|tanned|emerald|gold|silver} Skin tone:1.3) with (Pupil-less:1.8) {pale white|gold|gray|topaz} eyes:1.3)", "negative_prompt": ""},
    "Goblin": {"prompt": "(Solo) 1Goblin, ({Deep Red|Orange|Yellow|Green} Skin tone:1.3)", "negative_prompt": ""},
    "Kobold": {"prompt": "(Solo) 1Kobold, ({Reddish Brown|Rusty Black|Blue|White|Green} Squamous Skin tone:1.3) with Burnt {Orange|Red} eyes", "negative_prompt": ""},
    "Lizardfolk": {"prompt": "(Solo) 1Lizardfolk, Reptilian like", "negative_prompt": ""},
    "Dragonkin": {"prompt": "(Solo) 1dragonkin who is part (human:0.6) and part (dragon:0.4)", "negative_prompt": ""},
    "Dragon": {"prompt": "(Solo) 1(dragon:1.5)", "negative_prompt": ""},
    "Sword": {"prompt": "(Solo) 1 magical talking sword with a detailed face carved into the hilt. The sword's blade is made of shining enchanted metal, glowing with faint blue runes. The hilt is ornately designed, with the face either looking wise or menacing. A mystical aura surrounds the sword, giving it a magical presence. The setting has a fantasy medieval style, and the face on the hilt is expressive, blending into the intricate metalwork", "negative_prompt": ""},
    "Undead": {"prompt": "(Solo) 1undead", "negative_prompt": ""},
    "Ghoul": {"prompt": "(Solo) 1Ghoul, (skeletal:0.5), rotting corps that has been animated by dark necromantic force", "negative_prompt": ""},
    "Hippo": {"prompt": "(Solo) 1Hippo-Human hybrid, (Human:0.6) (Hippo:0.4), head of a Hippo", "negative_prompt": ""}
}