HAIR_COLOUR_DATA = {
    "No hair": {"prompt": "", "negative_prompt": ""},
    "Ash Blonde": {"prompt": "and Ash Blonde colored hair", "negative_prompt": ""},
    "Auburn": {"prompt": "and Auburn colored hair", "negative_prompt": ""},
    "Black": {"prompt": "and Black colored hair", "negative_prompt": ""},
    "Blonde": {"prompt": "and Blonde colored hair", "negative_prompt": ""},
    "Blue": {"prompt": "and Blue colored hair", "negative_prompt": ""},
    "Bright Orange": {"prompt": "and Bright Orange colored hair", "negative_prompt": ""},
    "Bright Red": {"prompt": "and Bright Red colored hair", "negative_prompt": ""},
    "Brown": {"prompt": "and Brown colored hair", "negative_prompt": ""},
    "Burnt Orange": {"prompt": "and Burnt Orange colored hair", "negative_prompt": ""},
    "Charcoal Gray": {"prompt": "and Charcoal Gray colored hair", "negative_prompt": ""},
    "Copper": {"prompt": "and Copper colored hair", "negative_prompt": ""},
    "Copper Orange": {"prompt": "and Copper Orange colored hair", "negative_prompt": ""},
    "Dark Brown": {"prompt": "and Dark Brown colored hair", "negative_prompt": ""},
    "Deep Purple": {"prompt": "and Deep Purple colored hair", "negative_prompt": ""},
    "Dirty Blonde": {"prompt": "and Dirty Blonde colored hair", "negative_prompt": ""},
    "Electric Blue": {"prompt": "and Electric Blue colored hair", "negative_prompt": ""},
    "Emerald Green": {"prompt": "and Emerald Green colored hair", "negative_prompt": ""},
    "Ginger": {"prompt": "and Ginger colored hair", "negative_prompt": ""},
    "Golden Blonde": {"prompt": "and Golden Blonde colored hair", "negative_prompt": ""},
    "Gray": {"prompt": "and Gray colored hair", "negative_prompt": ""},
    "Green": {"prompt": "and Green colored hair", "negative_prompt": ""},
    "Hot Pink": {"prompt": "and Hot Pink colored hair", "negative_prompt": ""},
    "Lavender": {"prompt": "and Lavender colored hair", "negative_prompt": ""},
    "Light Blonde": {"prompt": "and Light Blonde colored hair", "negative_prompt": ""},
    "Light Brown": {"prompt": "and Light Brown colored hair", "negative_prompt": ""},
    "Light Turquoise": {"prompt": "and Light Turquoise colored hair", "negative_prompt": ""},
    "Medium Brown": {"prompt": "and Medium Brown colored hair", "negative_prompt": ""},
    "Mint Green": {"prompt": "and Mint Green colored hair", "negative_prompt": ""},
    "Navy Blue": {"prompt": "and Navy Blue colored hair", "negative_prompt": ""},
    "Olive Green": {"prompt": "and Olive Green colored hair", "negative_prompt": ""},
    "Orange": {"prompt": "and Orange colored hair", "negative_prompt": ""},
    "Pastel Pink": {"prompt": "and Pastel Pink colored hair", "negative_prompt": ""},
    "Pink": {"prompt": "and Pink colored hair", "negative_prompt": ""},
    "Platinum Blonde": {"prompt": "and Platinum Blonde colored hair", "negative_prompt": ""},
    "Purple": {"prompt": "and Purple colored hair", "negative_prompt": ""},
    "Rainbow": {"prompt": "and Rainbow colored hair", "negative_prompt": ""},
    "Red": {"prompt": "and Red colored hair", "negative_prompt": ""},
    "Red-Orange": {"prompt": "and Red-Orange colored hair", "negative_prompt": ""},
    "Rose Pink": {"prompt": "and Rose Pink colored hair", "negative_prompt": ""},
    "Salt and Pepper": {"prompt": "and Salt and Pepper colored hair", "negative_prompt": ""},
    "Silver": {"prompt": "and Silver colored hair", "negative_prompt": ""},
    "Sky Blue": {"prompt": "and Sky Blue colored hair", "negative_prompt": ""},
    "Steel Gray": {"prompt": "and Steel Gray colored hair", "negative_prompt": ""},
    "Strawberry Blonde": {"prompt": "and Strawberry Blonde colored hair", "negative_prompt": ""},
    "Teal": {"prompt": "and Teal colored hair", "negative_prompt": ""},
    "Teal Turquoise": {"prompt": "and Teal Turquoise colored hair", "negative_prompt": ""},
    "Turquoise": {"prompt": "and Turquoise colored hair", "negative_prompt": ""},
    "Unnatural Colors": {"prompt": "and Unnatural Colors colored hair", "negative_prompt": ""},
    "Violet": {"prompt": "and Violet colored hair", "negative_prompt": ""},
    "White": {"prompt": "and White colored hair", "negative_prompt": ""},
}