CLOTHES_STYLE_DATA = {
    "Adventurer’s Gear": {"prompt": "wearing Adventurer’s Gear", "negative_prompt": ""},
    "Assassin’s Garb": {"prompt": "wearing Assassin’s Garb", "negative_prompt": ""},
    "Barbarian Furs": {"prompt": "wearing Barbarian Furs", "negative_prompt": ""},
    "Bardic Costume": {"prompt": "wearing Bardic Costume", "negative_prompt": ""},
    "Bikers": {"prompt": "wearing Bikers Garb", "negative_prompt": ""},
    "Cleric Vestments": {"prompt": "wearing Cleric Vestments", "negative_prompt": ""},
    "Courtier’s Dress": {"prompt": "wearing Courtier’s Dress", "negative_prompt": ""},
    "Drow Attire": {"prompt": "wearing Drow Attire", "negative_prompt": ""},
    "Druidic Garments": {"prompt": "wearing Druidic Garments", "negative_prompt": ""},
    "Hermit’s Garb": {"prompt": "wearing Hermit’s Garb", "negative_prompt": ""},
    "Leather Jacket": {"prompt": "wearing Leather Jacket", "negative_prompt": ""},
    "Long Leather Trench Coat": {"prompt": "wearing Long Leather Trench Coat", "negative_prompt": ""},
    "Long Trench Coat": {"prompt": "wearing Long Trench Coat", "negative_prompt": ""},
    "Lower class garb": {"prompt": "wearing Lower class garb", "negative_prompt": ""},
    "Mage Robes": {"prompt": "wearing Mage Robes", "negative_prompt": ""},
    "Merchant’s Clothing": {"prompt": "wearing Merchant’s Clothing", "negative_prompt": ""},
    "Middle class garb": {"prompt": "wearing Middle class garb", "negative_prompt": ""},
    "Monk Robes": {"prompt": "wearing Monk Robes", "negative_prompt": ""},
    "Noble Attire": {"prompt": "wearing Noble Attire", "negative_prompt": ""},
    "Paladin Plate": {"prompt": "wearing Paladin Plate", "negative_prompt": ""},
    "Pirate’s Clothing": {"prompt": "wearing Pirate’s Clothing", "negative_prompt": ""},
    "rags": {"prompt": "wearing rags", "negative_prompt": ""},
    "Ranger Outfit": {"prompt": "wearing Ranger Outfit", "negative_prompt": ""},
    "Rogue’s Outfit": {"prompt": "wearing Rogue’s Outfit", "negative_prompt": ""},
    "Sailor’s Gear": {"prompt": "wearing Sailor’s Gear", "negative_prompt": ""},
    "Scholar’s Robes": {"prompt": "wearing Scholar’s Robes", "negative_prompt": ""},
    "Upper class garb": {"prompt": "wearing Upper class garb", "negative_prompt": ""},
    "Warrior’s Armor": {"prompt": "wearing Warrior’s Armor", "negative_prompt": ""},
    "Topless": {"prompt": "is topless and wearing just {shorts|baggy trousers} ", "negative_prompt": "SFW, Safe for work, clothes"},
    "Naked": {"prompt": "is fully naked", "negative_prompt": "SFW, Safe for work, clothes"},
}