BEARD_STYLE_DATA = {
# =========================
# AD&D / Base Beard
# =========================
    "No Beard": {"prompt": "No Beard", "negative_prompt": "Beard"},
    "Anchor": {"prompt": "{short|medium|long} Anchor style {wavy|straight|slightly curled} beard", "negative_prompt": ""},
    "Balbo": {"prompt": "{short|medium} Balbo style {straight|slightly wavy} beard, {neatly trimmed|sharply groomed|slightly rugged}", "negative_prompt": ""},
    "Bandholz": {"prompt": "{long|very long} Bandholz style {scruffy|wavy|coarse} beard, {full and natural|slightly unruly|well groomed}", "negative_prompt": ""},
    "Chin strap": {"prompt": "{thin|medium|defined} chin strap beard, {cleanly shaped|neatly trimmed|subtle}", "negative_prompt": ""},
    "Circle Beard": {"prompt": "Circle Beard style {short|medium} beard, {neatly trimmed|cleanly groomed|slightly rugged}", "negative_prompt": ""},
    "Ducktail": {"prompt": "{medium|long} Ducktail style {straight|slightly wavy} beard, {neatly shaped|tapered and groomed|full at the chin}", "negative_prompt": ""},
    "Extended Goatee": {"prompt": "{short|medium|pointed} Extended Goatee style beard, {neatly trimmed|sharply groomed|slightly rugged}", "negative_prompt": ""},
    "French Fork": {"prompt": "{Long|Short} French Fork style {Wavy|Straight|Curvy} beard", "negative_prompt": ""},
    "Full Beard": {"prompt": "{short|medium|long|very long} full beard, {neatly groomed|naturally rugged|thick and well kept}, with {trimmed|slightly unruly|full} edges", "negative_prompt": ""},
    "Full Polished": {"prompt": "{short|medium|long} Full Polished style beard, {smoothly groomed|carefully trimmed|precisely shaped}", "negative_prompt": ""},
    "Garibaldi": {"prompt": "{medium|long|very long} Garibaldi style {wavy|slightly curly|natural} beard, {full and rounded|thick and natural|slightly unruly}", "negative_prompt": ""},
    "Goatee": {"prompt": "{short|medium|pointed} Goatee style beard, {neatly trimmed|sharply groomed|slightly rugged}", "negative_prompt": ""},
    "Handlebar Mustache": {"prompt": "{short|medium|full} Handlebar Mustache style facial hair, {neatly groomed|dramatically curled|slightly rugged}", "negative_prompt": ""},
    "Hipster": {"prompt": "{short|medium|long} Hipster style {scruffy|coarse|wavy} beard, {slightly unruly|full and natural|carefully groomed}", "negative_prompt": ""},
    "Hollywoodian": {"prompt": "{short|medium} Hollywoodian style boxed beard, {neatly trimmed|cleanly shaped|slightly rugged}", "negative_prompt": ""},
    "Imperial": {"prompt": "{elegant|sharply groomed|slightly curled} Imperial style facial hair", "negative_prompt": ""},
    "Kalamazoo": {"prompt": "{long|very long} Kalamazoo style {coarse|wavy|straight} beard, {full and rugged|naturally thick|slightly unruly}", "negative_prompt": ""},
    "Klingon": {"prompt": "{short|medium} Klingon style pointed beard, {sharp and groomed|rugged|slightly wild}", "negative_prompt": ""},
    "Long Beard": {"prompt": "{long|very long|flowing} beard, {thick|full|slightly wavy}, {carefully groomed|naturally rugged|slightly unruly}", "negative_prompt": ""},
    "Lumberjack": {"prompt": "{long|very long} Lumberjack style {coarse|thick|wavy} beard, {full and rugged|naturally heavy|slightly unruly}", "negative_prompt": ""},
    "Mutton Chops": {"prompt": "{short|medium|long} Mutton Chops style {thick|full|slightly rugged} side facial hair", "negative_prompt": ""},
    "Napoleon": {"prompt": "{short|medium} Napoleon style boxed beard, {neatly groomed|sharply trimmed|slightly rugged}", "negative_prompt": ""},
    "Old Wizard": {"prompt": "{long|very long|flowing} Old Wizard style beard, {white|grey|silver} and {wavy|straight|slightly tangled}", "negative_prompt": ""},
    "Pointed": {"prompt": "{short|medium|long} Pointed style pointed beard, {neatly groomed|sharply tapered|slightly rugged}", "negative_prompt": ""},
    "Power": {"prompt": "{short|medium|full} Power style beard, {neatly trimmed|thick and natural|carefully groomed}", "negative_prompt": ""},
    "Royale": {"prompt": "{short|medium|long} Royale style {wavy|straight|slightly curled} beard, {neatly groomed|full and natural|slightly rugged}", "negative_prompt": ""},
    "Russian": {"prompt": "{long|very long} Russian style {straight|wavy|coarse} beard, {full and heavy|naturally rugged|carefully groomed}", "negative_prompt": ""},
    "Scruffy": {"prompt": "{short|medium|long} scruffy beard, {messy|coarse|wavy}, naturally unkempt", "negative_prompt": ""},
    "Shadow": {"prompt": "{very short|short|medium} Shadow style stubble beard, {scruffy|neatly groomed|natural}", "negative_prompt": ""},
    "Shaggy": {"prompt": "{Medium|Long} Shaggy style Scruffy beard", "negative_prompt": ""},
    "Shenandoah": {"prompt": "{medium|long} Shenandoah style {wavy|straight|slightly curled} beard, {full and rounded|naturally thick|carefully groomed}", "negative_prompt": ""},
    "Sideburns": {"prompt": "{short|medium|long} sideburns, {neatly trimmed|full|slightly rugged}", "negative_prompt": ""},
    "Soul Patch": {"prompt": "{small|defined|subtle} soul patch beneath the lower lip", "negative_prompt": ""},
    "Stubble": {"prompt": "{light|medium|heavy} beard stubble, {evenly distributed|natural|slightly rugged}", "negative_prompt": ""},
    "Tapered": {"prompt": "{Short|Medium} Tapered style {Straight|Wavy} beard", "negative_prompt": ""},
    "Thin": {"prompt": "short Thin style fine beard", "negative_prompt": ""},
    "Van Dyke": {"prompt": "{short|medium|long} Van Dyke beard, {sharply pointed|neatly groomed|slightly rugged}", "negative_prompt": ""},
    "Verdi": {"prompt": "{medium|long} Verdi style beard, {full and rounded|carefully groomed|slightly wavy}", "negative_prompt": ""},
    "Viking Long": {"prompt": "{long|very long|braided} Viking Long style beard, {thick and rugged|wavy and full|naturally heavy}", "negative_prompt": ""},
    "Yeard": {"prompt": "{long|very long} Yeard style {straight|wavy|coarse} beard, {full and natural|slightly unruly|carefully groomed}", "negative_prompt": ""},
    "Zappa": {"prompt": "{short|medium} Zappa style facial hair, {neatly groomed|slightly rugged|sharply shaped}", "negative_prompt": ""},

# =========================
# Sci-Fi / Cyberpunk Beards
# =========================

    "Neon Goatee": {"prompt": "Goatee style beard with Neon highlights, Cyberpunk style", "negative_prompt": ""},
    "Cyberpunk Stubble": {"prompt": "Short Stubble with subtle tech/glow accents, futuristic style", "negative_prompt": ""},
    "Shaved Pattern Beard": {"prompt": "Medium beard with shaved geometric patterns, cyberpunk aesthetic", "negative_prompt": ""},
    "Holographic Beard": {"prompt": "Short to medium beard with holographic color effect, Sci-Fi style", "negative_prompt": ""},
    "Tech Beard": {"prompt": "Scruffy beard integrated with cybernetic implants, cyberpunk style", "negative_prompt": ""},
    "Wire-Lined Beard": {"prompt": "Beard with fine metallic wire accents, futuristic Cyberpunk look", "negative_prompt": ""},
    "Viral Patch": {"prompt": "Small patchy beard with neon or glowing tips, Sci-Fi aesthetic", "negative_prompt": ""},
    "Chrome Beard": {"prompt": "Medium to long beard with metallic chrome sheen, Cyberpunk style", "negative_prompt": ""},
    "LED Stubble": {"prompt": "Very short stubble with tiny embedded LED strands, futuristic look", "negative_prompt": ""},
    "Augmented Soul Patch": {"prompt": "Soul Patch with tech enhancements or glowing accents, Cyberpunk style", "negative_prompt": ""},
}