EMOTION_DATA = {
    "Neutral ": {"prompt": "showing a Neutral expression", "negative_prompt": ""},
    "Anger": {"prompt": "showing the expression of Anger", "negative_prompt": ""},
    "Anticipation": {"prompt": "showing the expression of Anticipation", "negative_prompt": ""},
    "Contempt": {"prompt": "showing the expression of Contempt", "negative_prompt": ""},
    "Despair": {"prompt": "showing the expression of Despair", "negative_prompt": ""},
    "Disgust": {"prompt": "showing the expression of Disgust", "negative_prompt": ""},
    "Embarrassment": {"prompt": "showing the expression of Embarrassment", "negative_prompt": ""},
    "Excitement": {"prompt": "showing the expression of Excitement", "negative_prompt": ""},
    "Fear": {"prompt": "showing the expression of Fear", "negative_prompt": ""},
    "Frustration": {"prompt": "showing the expression of Frustration", "negative_prompt": ""},
    "Gratitude": {"prompt": "showing the expression of Gratitude", "negative_prompt": ""},
    "Guilt": {"prompt": "showing the expression of Guilt", "negative_prompt": ""},
    "Hope": {"prompt": "showing the expression of Hope", "negative_prompt": ""},
    "Joy": {"prompt": "showing the expression of Joy", "negative_prompt": ""},
    "Loneliness": {"prompt": "showing the expression of Loneliness", "negative_prompt": ""},
    "Pride": {"prompt": "showing the expression of Pride", "negative_prompt": ""},
    "Regret": {"prompt": "showing the expression of Regret", "negative_prompt": ""},
    "Sadness": {"prompt": "showing the expression of Sadness", "negative_prompt": ""},
    "Shame": {"prompt": "showing the expression of Shame", "negative_prompt": ""},
    "Surprise": {"prompt": "showing the expression of Surprise", "negative_prompt": ""},
    "Trust": {"prompt": "showing the expression of Trust", "negative_prompt": ""},
}