HAIR_STYLE_DATA = {
    "Bald": {"prompt": "with a bald head", "negative_prompt": "hair on head"},
    "Afro": {"prompt": "with Afro Hair", "negative_prompt": ""},
    "Beehive haircut": {"prompt": "with Beehive haircut", "negative_prompt": ""},
    "Bleached spikes": {"prompt": "with Bleached spikes", "negative_prompt": ""},
    "Blunt bob": {"prompt": "with Blunt bob", "negative_prompt": ""},
    "Bob": {"prompt": "with Bob haircut", "negative_prompt": ""},
    "Bowl cut": {"prompt": "with bowl cut hair", "negative_prompt": ""},
    "Box braids": {"prompt": "with Box braids", "negative_prompt": ""},
    "Bushy": {"prompt": "with Bushy hair", "negative_prompt": ""},
    "Buzz cut": {"prompt": "with Buzz cut", "negative_prompt": ""},
    "Chignon": {"prompt": "with Chignon", "negative_prompt": ""},
    "Cloudy": {"prompt": "with Cloudy hair", "negative_prompt": ""},
    "Cornrows Hair": {"prompt": "with Cornrows Hair", "negative_prompt": ""},
    "Crimped": {"prompt": "with Crimped hair", "negative_prompt": ""},
    "Curly bob": {"prompt": "with Curly bob", "negative_prompt": ""},
    "Curly Frizzy": {"prompt": "with Curly Frizzy Hair", "negative_prompt": ""},
    "Double Bun": {"prompt": "with Double Bun", "negative_prompt": ""},
    "Dreadlocks": {"prompt": "with Dreadlocks", "negative_prompt": ""},
    "Fishtail braid": {"prompt": "with Fishtail braid", "negative_prompt": ""},
    "French twist": {"prompt": "with French twist", "negative_prompt": ""},
    "High Ponytail": {"prompt": "with High Ponytail", "negative_prompt": ""},
    "Long ponytail": {"prompt": "with Long ponytail", "negative_prompt": ""},
    "Long straight": {"prompt": "with Long straight hair", "negative_prompt": ""},
    "Long with bangs": {"prompt": "with Long hair with bangs", "negative_prompt": ""},
    "Loose Curly Afro": {"prompt": "with Loose Curly Afro hair", "negative_prompt": ""},
    "Mohawk": {"prompt": "with Mohawk", "negative_prompt": ""},
    "Pixie cut": {"prompt": "with Pixie cut", "negative_prompt": ""},
    "Pompadour haircut": {"prompt": "with Pompadour haircut", "negative_prompt": ""},
    "Quiff haircut": {"prompt": "with Quiff haircut", "negative_prompt": ""},
    "Ringlets": {"prompt": "with Hair ringlets", "negative_prompt": ""},
    "Short": {"prompt": "with Short hair", "negative_prompt": ""},
    "Short curly": {"prompt": "with Short curly hair", "negative_prompt": ""},
    "Short curly pixie cut": {"prompt": "with Short curly pixie cut", "negative_prompt": ""},
    "Shoulder length straight": {"prompt": "with Shoulder length straight hair", "negative_prompt": ""},
    "Shoulder Length with Bangs": {"prompt": "with Shoulder Length Hair with Bangs", "negative_prompt": ""},
    "Side braid": {"prompt": "with Side braid", "negative_prompt": ""},
    "Side Part Comb-Over": {"prompt": "with Side Part Comb-Over Hairstyle With High Fade", "negative_prompt": ""},
    "Spiky hair": {"prompt": "with Spiky hair", "negative_prompt": ""},
    "Stacked Curls in Short Bob": {"prompt": "with Stacked Curls in Short Bob", "negative_prompt": ""},
    "Tomboy Cut": {"prompt": "with Tomboy Cut", "negative_prompt": ""},
    "Twin braids": {"prompt": "with Twin braids", "negative_prompt": ""},
    "Twintails": {"prompt": "with Twintails hair", "negative_prompt": ""},
    "Updo": {"prompt": "with Updo hair", "negative_prompt": ""},
    "Very long wave": {"prompt": "with Very long wave hair", "negative_prompt": ""},
    "Wavy": {"prompt": "with Wavy hair", "negative_prompt": ""},
}