ETHNICITY_DATA = {
    "None": {"prompt": "", "negative_prompt": ""},
    "Aboriginal Australian": {"prompt": "(Ethnicity is Aboriginal Australian) and they have Deep skin tones, broad nosed, and dark brown eyes", "negative_prompt": ""},
    "Ancient Gauls": {"prompt": "(Ethnicity is Ancient Gauls) and they have fair to medium skin tones, strong facial features, high cheekbones, and a variety of eye colors, often blue or green.", "negative_prompt": ""},
    "African American": {"prompt": "(Ethnicity is African American) and they have light and dark skin tones, with brown eyes, and varying facial features", "negative_prompt": ""},
    "Arab": {"prompt": "(Ethnicity is Arab) and they have Olive to dark skin, almond-shaped eyes, and typically dark brown eyes", "negative_prompt": ""},
    "Argentine": {"prompt": "(Ethnicity is Argentine) and they have Light to medium skin tone, diverse facial features, and {brown|hazel} eyes", "negative_prompt": ""},
    "Ashkenazi Jewish": {"prompt": "(Ethnicity is Ashkenazi Jewish) and they have Light to medium skin tone, varied facial features, and {blue|dark brown} eyes", "negative_prompt": ""},
    "Baklunish": {"prompt": "(Ethnicity is Baklunish) and they have Olive to bronze skin, sharp features, and dark eyes", "negative_prompt": ""},
    "Basque": {"prompt": "(Ethnicity is Basque) and they have Light to medium skin tone, strong jawlines, and {brown|green} eyes", "negative_prompt": ""},
    "Bedine": {"prompt": "(Ethnicity is Bedine) and they have Medium to dark skin tone, high cheekbones, and dark brown eyes", "negative_prompt": ""},
    "Bengali": {"prompt": "(Ethnicity is Bengali) and they have medium to dark skin tone, round faces, and dark brown eyes", "negative_prompt": ""},
    "Berber": {"prompt": "(Ethnicity is Berber) and they have Light to medium olive skin, prominent cheekbones, and dark brown eyes", "negative_prompt": ""},
    "Brazilian": {"prompt": "(Ethnicity is Brazilian) and they have Diverse skin tones, a mix of facial features, and {brown|hazel} eyes", "negative_prompt": ""},
    "British": {"prompt": "(Ethnicity is British) and they have Light to medium skin tone, varied features, and {blue|green|brown} eyes", "negative_prompt": ""},
    "Calishite": {"prompt": "(Ethnicity is Calishite) and they have Olive to dark skin, broad nosed, and dark eyes", "negative_prompt": ""},
    "Chilean": {"prompt": "(Ethnicity is Chilean) and they have Light to medium skin tone, varied features, and brown eyes", "negative_prompt": ""},
    "Chondathans": {"prompt": "(Ethnicity is Chondathans) and they have Light to olive skin, varied features, with {green|brown} eyes", "negative_prompt": ""},
    "Cuban": {"prompt": "(Ethnicity is Cuban) and they have light to dark skin tone, diverse features, and brown eyes", "negative_prompt": ""},
    "Damaran": {"prompt": "(Ethnicity is Damaran) and they have Pale to tan skin, broad features, and {blue|brown} eyes", "negative_prompt": ""},
    "Dominican": {"prompt": "(Ethnicity is Dominican) and they have medium to dark skin tone, diverse features,and brown eyes", "negative_prompt": ""},
    "Fijian": {"prompt": "(Ethnicity is Fijian) and they have Deep brown skin tones, broad faces, and dark brown eyes", "negative_prompt": ""},
    "Finnish": {"prompt": "(Ethnicity is Finnish) and they have Light skin tones, fine features, and {blue|gray} eyes", "negative_prompt": ""},
    "Flan": {"prompt": "(Ethnicity is Flan) and they have Dark bronze skin, high cheekbones, with dark eyes", "negative_prompt": ""},
    "French": {"prompt": "(Ethnicity is French) and they have Light to medium skin tone, varied features, and {blue|green|brown} eyes", "negative_prompt": ""},
    "German": {"prompt": "(Ethnicity is German) and they have Light to medium skin tone, varied facial features, and {blue|green|brown} eyes", "negative_prompt": ""},
    "Greek": {"prompt": "(Ethnicity is Greek) and they have LightOlive to medium skin tones, strong features,and {brown|hazel} eyes", "negative_prompt": ""},
    "Han Chinese": {"prompt": "(Ethnicity is Han Chinese) and they have Light to medium skin tone, round faces, and dark brown eyes", "negative_prompt": ""},
    "Hawaiian": {"prompt": "(Ethnicity is Hawaiian) and they have Medium to deep tan skin, broad features, with dark brown eyes", "negative_prompt": ""},
    "Illuskan": {"prompt": "(Ethnicity is Illuskan) and they have Pale to light skin, tall, strong features, and {blue|grey} eyes", "negative_prompt": ""},
    "Indian": {"prompt": "(Ethnicity is Indian) and they have medium to dark skin tone, brown eyes, and varying facial features", "negative_prompt": ""},
    "Inuit": {"prompt": "(Ethnicity is Inuit) and they have Light to medium brown skin, brown eyes, broad faces, and prominent cheekbones", "negative_prompt": ""},
    "Irish": {"prompt": "(Ethnicity is Irish) and they have Light skin, and {blue|green} eyes, with freckled complexion", "negative_prompt": ""},
    "Italian": {"prompt": "(Ethnicity is Italian) and they have Olive to light skin, {brown|hazel} eyes, and strong facial features", "negative_prompt": ""},
    "Japanese": {"prompt": "(Ethnicity is Japanese) and they have Light skin, brown eyes, delicate facial features, and {round|oval} face shape", "negative_prompt": ""},
    "Jewish": {"prompt": "(Ethnicity is Jewish) and they have often medium skin tones, brown eyes, and diverse facial structures", "negative_prompt": ""},
    "Korean": {"prompt": "(Ethnicity is Korean) and they have Light to medium skin, brown eyes, soft facial features, and smaller nose bridge", "negative_prompt": ""},
    "Kurdish": {"prompt": "(Ethnicity is Kurdish) and they have Olive to medium skin, brown eyes, prominent nose, and high cheekbones", "negative_prompt": ""},
    "Maasai": {"prompt": "(Ethnicity is Maasai) and they have Dark skin, brown eyes, elongated facial features, tall and slender build", "negative_prompt": ""},
    "M?ori": {"prompt": "(Ethnicity is M?ori) and they have Light brown to olive skin, brown eyes, strong jawlines, and full lips", "negative_prompt": ""},
    "Mulan": {"prompt": "(Ethnicity is Mulan) and they have Chinese heritage, light skin, brown eyes, and round face", "negative_prompt": ""},
    "Native American": {"prompt": "(Ethnicity is Native American) and they have Light to medium brown skin, brown eyes, high cheekbones, and a straight nose", "negative_prompt": ""},
    "Nordic": {"prompt": "(Ethnicity is Nordic) and they have Light skin, and {blue|grey} eyes, and angular facial features", "negative_prompt": ""},
    "Oeridians": {"prompt": "(Ethnicity is Oeridian) and they have Light to medium skin tone, sharp facial features, and blue or gray eyes", "negative_prompt": ""},
    "Pakistani": {"prompt": "(Ethnicity is Pakistani) and they have Medium to dark skin, brown eyes, and varied facial features", "negative_prompt": ""},
    "Persian (Iranian)": {"prompt": "(Ethnicity is Persian (Iranian)) and they have Light to olive skin, {brown|hazel} eyes, prominent nose, and high cheekbones", "negative_prompt": ""},
    "Polish": {"prompt": "(Ethnicity is Polish) and they have Light skin, {blue|green} eyes, and round facial features", "negative_prompt": ""},
    "Puerto Rican": {"prompt": "(Ethnicity is Puerto Rican) and they have Light to medium brown skin, brown eyes, and a blend of European, African, and Indigenous features", "negative_prompt": ""},
    "Punjabi": {"prompt": "(Ethnicity is Punjabi) and they have Medium to dark skin, brown eyes, and strong facial features", "negative_prompt": ""},
    "Rashemi": {"prompt": "(Ethnicity is Rashemi) and they have Medium to olive skin tone, strong noses, and dark brown eyes", "negative_prompt": ""},
    "Rhennee": {"prompt": "(Ethnicity is Rhennee) and they have Medium skin tone, round faces, and hazel or brown eyes", "negative_prompt": ""},
    "Roma (Gypsy)": {"prompt": "(Ethnicity is Roma (Gypsy)) and they have Olive to dark skin, brown eyes, and strong facial features", "negative_prompt": ""},
    "Roman": {"prompt": "(Ethnicity is Roman) and they have strong, symmetrical facial structures, prominent noses, well-defined jawlines, olive to fair skin tones, and a wide variety of eye colors, typically brown, hazel, or green.", "negative_prompt": ""},
    "Russian": {"prompt": "(Ethnicity is Russian) and they have Light skin, {blue|green|grey} eyes, and high cheekbones", "negative_prompt": ""},
    "Samoan": {"prompt": "(Ethnicity is Samoan) and they have Light to dark brown skin, brown eyes, broad build, and strong facial features", "negative_prompt": ""},
    "Scandinavian": {"prompt": "(Ethnicity is Scandinavian) and they have Light skin, {blue|green} eyes, high cheekbones, and angular features", "negative_prompt": ""},
    "Scottish": {"prompt": "(Ethnicity is Scottish) and they have Light skin, {blue|green} eyes, sometimes freckled, strong jawline", "negative_prompt": ""},
    "Sephardic Jewish": {"prompt": "(Ethnicity is Sephardic Jewish) and they have Olive to light skin, brown eyes, and diverse facial features", "negative_prompt": ""},
    "Shou": {"prompt": "(Ethnicity is Shou) and they have Light to medium skin tone, delicate features, and dark brown eyes", "negative_prompt": ""},
    "Somali": {"prompt": "(Ethnicity is Somali) and they have Dark skin, brown eyes, fine facial features, tall and slender", "negative_prompt": ""},
    "Spanish": {"prompt": "(Ethnicity is Spanish) and they have Light to olive skin, {brown|hazel} eyes, and diverse facial features", "negative_prompt": ""},
    "Suel": {"prompt": "(Ethnicity is Suel) and they have Fair to light skin tone, angular cheekbones, and green or blue eyes", "negative_prompt": ""},
    "Swedish": {"prompt": "(Ethnicity is Swedish) and they have Light {blue|green} eyes, fair complexion, high cheekbones, and a generally tall stature", "negative_prompt": ""},
    "Tethyrian": {"prompt": "(Ethnicity is Tethyrian) and they have {brown|hazel} eyes, medium to fair skin, and a diverse range of facial features", "negative_prompt": ""},
    "Thai": {"prompt": "(Ethnicity is Thai) and they have Dark brown eyes, warm skin tones, and delicate facial features with a rounded face shape", "negative_prompt": ""},
    "Tongan": {"prompt": "(Ethnicity is Tongan) and they have Dark brown eyes, medium to deep skin tones, broad nose, and strong prominent facial features", "negative_prompt": ""},
    "Turami": {"prompt": "(Ethnicity is Turami) and they have Deep brown eyes, rich skin tones ranging from olive to dark, with strong well-defined features", "negative_prompt": ""},
    "Turkish": {"prompt": "(Ethnicity is Turkish) and they have {brown|hazel} eyes, olive to light skin, with sharp defined facial features and high cheekbones", "negative_prompt": ""},
    "Ukrainian": {"prompt": "(Ethnicity is Ukrainian) and they have Light to medium {blue|green|grey} eyes, fair to light skin, with sharp angular facial features", "negative_prompt": ""},
    "Vietnamese": {"prompt": "(Ethnicity is Vietnamese) and they have Dark brown eyes, warm to medium skin tones, with soft delicate facial features and a slender face shape", "negative_prompt": ""},
    "Welsh": {"prompt": "(Ethnicity is Welsh) and they have Light {blue|green|grey} eyes, fair skin, with a variety of facial structures{|, with a strong jawline|, with a strong jawline}", "negative_prompt": ""},
    "Yoruba": {"prompt": "(Ethnicity is Yoruba) and they have Dark brown eyes, deep skin tones, prominent cheekbones, and well-defined facial features", "negative_prompt": ""},
    "Zulu": {"prompt": "(Ethnicity is Zulu) and they have Dark brown eyes, deep skin tones, high cheekbones, and strong pronounced facial features", "negative_prompt": ""}
}