SCENE_DATA = {
    "Plain White": {"prompt": "(Plain Simple Background, (White Background))", "negative_prompt": ""},
    "Plain Black": {"prompt": "(Plain Black Background)", "negative_prompt": ""},
    "Plain Red": {"prompt": "(Plain Simple Background, (Red Background))", "negative_prompt": ""},
    "Plain Green": {"prompt": "(Plain Simple Background, (Green Background))", "negative_prompt": ""},
    "Plain Blue": {"prompt": "(Plain Simple Background, (Blue Background))", "negative_prompt": ""},
    "Plain Yellow": {"prompt": "(Plain Simple Background, (Yellow Background))", "negative_prompt": ""},
    "Magic Pink": {"prompt": "(Plain Simple Background, (the color Fuchsia Background))", "negative_prompt": ""},
    "Green Screen": {"prompt": "(Plain Simple Background, (Green Pantone Background))", "negative_prompt": ""},
    "Chroma key Blue": {"prompt": '(Plain Simple Background, (The Color "Absolute Zero" Background))', "negative_prompt": ''},
    "Ancient Ruins": {"prompt": "Ancient Ruins In Background", "negative_prompt": ""},
    "Beach Sunset": {"prompt": "Beach Sunset In Background", "negative_prompt": ""},
    "Canyon Vista": {"prompt": "Canyon Vista In Background", "negative_prompt": ""},
    "Charming Village": {"prompt": "Charming Village In Background", "negative_prompt": ""},
    "Coastal Cliffs": {"prompt": "Coastal Cliffs In Background", "negative_prompt": ""},
    "Countryside Farm": {"prompt": "Countryside Farm In Background", "negative_prompt": ""},
    "Desert Dunes": {"prompt": "Desert Dunes In Background", "negative_prompt": ""},
    "Historic Castle": {"prompt": "Historic Castle In Background", "negative_prompt": ""},
    "Lush Forest": {"prompt": "Lush Forest In Background", "negative_prompt": ""},
    "Mountain Range": {"prompt": "Mountain Range In Background", "negative_prompt": ""},
    "Ocean Horizon": {"prompt": "Ocean Horizon In Background", "negative_prompt": ""},
    "Rolling Hills": {"prompt": "Rolling Hills In Background", "negative_prompt": ""},
    "Rustic Vineyard": {"prompt": "Rustic Vineyard In Background", "negative_prompt": ""},
    "Serene Lake": {"prompt": "Serene Lake In Background", "negative_prompt": ""},
    "Snow-Capped Peaks": {"prompt": "Snow-Capped Peaks In Background", "negative_prompt": ""},
    "Snowy Forest": {"prompt": "Snowy Forest In Background", "negative_prompt": ""},
    "Sunset Over the Plains": {"prompt": "Sunset Over the Plains In Background", "negative_prompt": ""},
    "Tropical Island": {"prompt": "Tropical Island In Background", "negative_prompt": ""},
    "Waterfall": {"prompt": "Waterfall In Background", "negative_prompt": ""},
    "Wildflower Meadow": {"prompt": "Wildflower Meadow In Background", "negative_prompt": ""},
    "Dutch countryside": {"prompt": "The background is A serene Dutch landscape featuring flat, open fields with vibrant green grass, winding canals reflecting the sky, and a scattering of traditional windmills under a vast, soft, cloudy sky", "negative_prompt": ""},
}