BEARD_COLOUR_DATA = {
    "No Beard": {"prompt": "", "negative_prompt": ""},
    "Ash Blonde": {"prompt": "which is Ash Blonde Colored", "negative_prompt": ""},
    "Auburn": {"prompt": "which is Auburn Colored", "negative_prompt": ""},
    "Black": {"prompt": "which is Black Colored", "negative_prompt": ""},
    "Blonde": {"prompt": "which is Blonde Colored", "negative_prompt": ""},
    "Blue": {"prompt": "which is Blue Colored", "negative_prompt": ""},
    "Bright Orange": {"prompt": "which is Bright Orange Colored", "negative_prompt": ""},
    "Bright Red": {"prompt": "which is Bright Red Colored", "negative_prompt": ""},
    "Brown": {"prompt": "which is Brown Colored", "negative_prompt": ""},
    "Burnt Orange": {"prompt": "which is Burnt Orange Colored", "negative_prompt": ""},
    "Charcoal Gray": {"prompt": "which is Charcoal Gray Colored", "negative_prompt": ""},
    "Copper": {"prompt": "which is Copper Colored", "negative_prompt": ""},
    "Copper Orange": {"prompt": "which is Copper Orange Colored", "negative_prompt": ""},
    "Dark Brown": {"prompt": "which is Dark Brown Colored", "negative_prompt": ""},
    "Deep Purple": {"prompt": "which is Deep Purple Colored", "negative_prompt": ""},
    "Dirty Blonde": {"prompt": "which is Dirty Blonde Colored", "negative_prompt": ""},
    "Electric Blue": {"prompt": "which is Electric Blue Colored", "negative_prompt": ""},
    "Emerald Green": {"prompt": "which is Emerald Green Colored", "negative_prompt": ""},
    "Ginger": {"prompt": "which is Ginger Colored", "negative_prompt": ""},
    "Golden Blonde": {"prompt": "which is Golden Blonde Colored", "negative_prompt": ""},
    "Gray": {"prompt": "which is Gray Colored", "negative_prompt": ""},
    "Green": {"prompt": "which is Green Colored", "negative_prompt": ""},
    "Hot Pink": {"prompt": "which is Hot Pink Colored", "negative_prompt": ""},
    "Lavender": {"prompt": "which is Lavender Colored", "negative_prompt": ""},
    "Light Blonde": {"prompt": "which is Light Blonde Colored", "negative_prompt": ""},
    "Light Brown": {"prompt": "which is Light Brown Colored", "negative_prompt": ""},
    "Light Turquoise": {"prompt": "which is Light Turquoise Colored", "negative_prompt": ""},
    "Medium Brown": {"prompt": "which is Medium Brown Colored", "negative_prompt": ""},
    "Mint Green": {"prompt": "which is Mint Green Colored", "negative_prompt": ""},
    "Navy Blue": {"prompt": "which is Navy Blue Colored", "negative_prompt": ""},
    "Olive Green": {"prompt": "which is Olive Green Colored", "negative_prompt": ""},
    "Orange": {"prompt": "which is Orange Colored", "negative_prompt": ""},
    "Pastel Pink": {"prompt": "which is Pastel Pink Colored", "negative_prompt": ""},
    "Pink": {"prompt": "which is Pink Colored", "negative_prompt": ""},
    "Platinum Blonde": {"prompt": "which is Platinum Blonde Colored", "negative_prompt": ""},
    "Purple": {"prompt": "which is Purple Colored", "negative_prompt": ""},
    "Rainbow": {"prompt": "which is Rainbow Colored", "negative_prompt": ""},
    "Red": {"prompt": "which is Red Colored", "negative_prompt": ""},
    "Red-Orange": {"prompt": "which is Red-Orange Colored", "negative_prompt": ""},
    "Rose Pink": {"prompt": "which is Rose Pink Colored", "negative_prompt": ""},
    "Salt and Pepper": {"prompt": "which is Salt and Pepper Colored", "negative_prompt": ""},
    "Silver": {"prompt": "which is Silver Colored", "negative_prompt": ""},
    "Sky Blue": {"prompt": "which is Sky Blue Colored", "negative_prompt": ""},
    "Steel Gray": {"prompt": "which is Steel Gray Colored", "negative_prompt": ""},
    "Strawberry Blonde": {"prompt": "which is Strawberry Blonde Colored", "negative_prompt": ""},
    "Teal": {"prompt": "which is Teal Colored", "negative_prompt": ""},
    "Teal Turquoise": {"prompt": "which is Teal Turquoise Colored", "negative_prompt": ""},
    "Turquoise": {"prompt": "which is Turquoise Colored", "negative_prompt": ""},
    "Unnatural Colors": {"prompt": "which is Unnatural Colors Colored", "negative_prompt": ""},
    "Violet": {"prompt": "which is Violet Colored", "negative_prompt": ""},
    "White": {"prompt": "which is White Colored", "negative_prompt": ""},
}