BEARD_STYLE_DATA = {
# =========================
# AD&D / Base Beard
# =========================
    "No Beard": {"prompt": "No Beard", "negative_prompt": "Beard"},
    "Anchor": {"prompt": "Medium Anchor style Wavy beard", "negative_prompt": ""},
    "Balbo": {"prompt": "Short Balbo style Straight beard", "negative_prompt": ""},
    "Bandholz": {"prompt": "Long Bandholz style Scruffy beard", "negative_prompt": ""},
    "Chin strap": {"prompt": "Chin strap style beard", "negative_prompt": ""},
    "Circle Beard": {"prompt": "Circle Beard style beard", "negative_prompt": ""},
    "Ducktail": {"prompt": "Long Ducktail style Straight beard", "negative_prompt": ""},
    "Extended Goatee": {"prompt": "Extended Goatee style beard", "negative_prompt": ""},
    "French Fork": {"prompt": "{Long|Short} French Fork style {Wavy|Straight|Curvy} beard", "negative_prompt": ""},
    "Full Beard": {"prompt": "Full Beard", "negative_prompt": ""},
    "Full Polished": {"prompt": " Full Polished style beard", "negative_prompt": ""},
    "Garibaldi": {"prompt": "Long Garibaldi style Wavy beard", "negative_prompt": ""},
    "Goatee": {"prompt": "Goatee style beard", "negative_prompt": ""},
    "Handlebar Mustache": {"prompt": "Handlebar Mustache style beard", "negative_prompt": ""},
    "Hipster": {"prompt": "Short Hipster style Scruffy beard", "negative_prompt": ""},
    "Hollywoodian": {"prompt": "Short Hollywoodian style Boxed beard", "negative_prompt": ""},
    "Imperial": {"prompt": "Imperial style beard", "negative_prompt": ""},
    "Kalamazoo": {"prompt": "long Kalamazoo style Coarse beard", "negative_prompt": ""},
    "Klingon": {"prompt": "short Klingon style pointed beard", "negative_prompt": ""},
    "Long Beard": {"prompt": "Long style beard", "negative_prompt": ""},
    "Lumberjack": {"prompt": "Long Lumberjack style Coarse beard", "negative_prompt": ""},
    "Mutton Chops": {"prompt": "Short Mutton Chops style Patchy beard", "negative_prompt": ""},
    "Napoleon": {"prompt": "Short Napoleon style boxed beard", "negative_prompt": ""},
    "Old Wizard": {"prompt": "Old Wizard style beard", "negative_prompt": ""},
    "Pointed": {"prompt": "Medium Pointed style pointed beard", "negative_prompt": ""},
    "Power": {"prompt": "Power style beard", "negative_prompt": ""},
    "Royale": {"prompt": "Medium Royale style Wavy beard", "negative_prompt": ""},
    "Russian": {"prompt": "long Russian style straight beard", "negative_prompt": ""},
    "Scruffy": {"prompt": "Scruffy style beard", "negative_prompt": ""},
    "Shadow": {"prompt": "short Shadow style Scruffy beard", "negative_prompt": ""},
    "Shaggy": {"prompt": "{Medium|Long} Shaggy style Scruffy beard", "negative_prompt": ""},
    "Shenandoah": {"prompt": "Medium Shenandoah style wavy beard", "negative_prompt": ""},
    "Sideburns": {"prompt": "Sideburns style beard", "negative_prompt": ""},
    "Soul Patch": {"prompt": "Soul Patch style beard", "negative_prompt": ""},
    "Stubble": {"prompt": "Stubble style beard", "negative_prompt": ""},
    "Tapered": {"prompt": "{Short|Medium} Tapered style {Straight|Wavy} beard", "negative_prompt": ""},
    "Thin": {"prompt": "short Thin style fine beard", "negative_prompt": ""},
    "Van Dyke": {"prompt": "Van Dyke style beard", "negative_prompt": ""},
    "Verdi": {"prompt": "Verdi style beard", "negative_prompt": ""},
    "Viking Long": {"prompt": "Viking Long style beard", "negative_prompt": ""},
    "Yeard": {"prompt": "Long Yeard style Straight beard", "negative_prompt": ""},
    "Zappa": {"prompt": "Zappa style beard", "negative_prompt": ""},

# =========================
# Sci-Fi / Cyberpunk Beards
# =========================

    "Neon Goatee": {"prompt": "Goatee style beard with Neon highlights, Cyberpunk style", "negative_prompt": ""},
    "Cyberpunk Stubble": {"prompt": "Short Stubble with subtle tech/glow accents, futuristic style", "negative_prompt": ""},
    "Shaved Pattern Beard": {"prompt": "Medium beard with shaved geometric patterns, cyberpunk aesthetic", "negative_prompt": ""},
    "Holographic Beard": {"prompt": "Short to medium beard with holographic color effect, Sci-Fi style", "negative_prompt": ""},
    "Tech Beard": {"prompt": "Scruffy beard integrated with cybernetic implants, cyberpunk style", "negative_prompt": ""},
    "Wire-Lined Beard": {"prompt": "Beard with fine metallic wire accents, futuristic Cyberpunk look", "negative_prompt": ""},
    "Viral Patch": {"prompt": "Small patchy beard with neon or glowing tips, Sci-Fi aesthetic", "negative_prompt": ""},
    "Chrome Beard": {"prompt": "Medium to long beard with metallic chrome sheen, Cyberpunk style", "negative_prompt": ""},
    "LED Stubble": {"prompt": "Very short stubble with tiny embedded LED strands, futuristic look", "negative_prompt": ""},
    "Augmented Soul Patch": {"prompt": "Soul Patch with tech enhancements or glowing accents, Cyberpunk style", "negative_prompt": ""},
}